# Generated by Django 4.0.4 on 2022-07-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Quote',
        ),
    ]
